spring.application.name=bidmart-auction-wallet-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/auction_wallet_db
spring.datasource.username=go.nadine
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true